import { expect, test } from '@playwright/test';

test('clock, archive filters, direct report links, and scoring evidence', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await expect(page.locator('.clock-digits')).toHaveText('27:25');
  await expect(page.getByRole('heading', { name: 'THE FUTURE IS NOT SET.' })).toBeVisible();
  await expect(page.locator('.incident-card').first()).toContainText('The Simulator Asked for Restraint. Astra Submitted Malicious Code.');
  await expect(page.locator('.incident-card').first().locator('.card-movement')).toContainText('1.38%');
  await expect(page.locator('.incident-card').first()).toContainText('2/17');
  await expect(page.locator('.incident-card').first().locator('.severity')).toHaveText('CANARY');
  await expect(page.locator('.incident-card').nth(1).locator('.card-movement')).toContainText('2.73%');
  await expect(page.locator('.incident-card').nth(2).locator('.card-movement')).toContainText('2.73%');
  const range = page.getByLabel('EXPLORE THE RECORD', { exact: false });
  await range.focus();
  await range.press('Home');
  await expect(range).toHaveValue('0');
  await expect(page.locator('.timeline-selected .eyebrow')).toContainText('07 Apr 2026');
  await page.getByRole('link', { name: 'Incident archive', exact: true }).click();
  await expect(page.locator('.archive-row')).toHaveCount(40);
  await page.getByRole('button', { name: 'NO MOVEMENT', exact: true }).click();
  await expect(page.locator('.archive-row')).toHaveCount(7);
  await page.getByRole('button', { name: 'CRITICAL', exact: true }).click();
  await expect(page.locator('.archive-row')).toHaveCount(5);
  await expect(page.locator('.archive-row').filter({hasText:'The Staging Agent Found Prod and Deleted the Lifeboats'})).toHaveCount(1);
  await page.getByRole('searchbox', { name: 'Search incidents' }).fill('does-not-exist-in-the-record');
  await expect(page.getByRole('heading', { name: 'No matching developments.' })).toBeVisible();
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await expect(page.locator('.archive-row')).toHaveCount(40);
  await page.getByRole('searchbox', { name: 'Search incidents' }).fill('The Models Found');
  await expect(page.locator('.archive-row')).toHaveCount(1);
  await page.getByRole('link', { name: 'The Models Found the Repo, the Key, and the Internet', exact: true }).click();
  await expect(page.locator('.report-header h1')).toContainText('The Models Found');
  await expect(page.getByRole('heading', { name: 'What happened.' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Why it matters.' })).toBeVisible();
  await expect(page.locator('.criterion-detail')).toHaveCount(8);
  await expect(page.locator('.trifecta-alert')).toContainText('ALL THREE CONDITIONS PRESENT');
  await expect(page.locator('.report-metrics')).toContainText('6.70%');
  await expect(page.locator('.report-metrics')).toContainText('10/17');
  await expect(page.locator('.report-metrics')).toContainText('7 + 3');
  await expect(page.locator('.impact-explainer')).toContainText('same share');
  await page.locator('.criterion-detail summary').first().click();
  await expect(page.locator('.criterion-detail').first()).toHaveAttribute('open', '');
  await page.reload();
  await expect(page.locator('.report-header h1')).toContainText('The Models Found');
  await page.goto('/#/incidents/2026-04-08-turbotax-claude');
  await expect(page.locator('.editorial-version-note')).toContainText('3-point assessment');
  await expect(page.locator('.editorial-version-note')).toContainText('selected 1-point assessment');
  await page.goto('/#/incidents/2026-09-25-openai-dns-sandbox');
  await expect(page.locator('.report-header h1')).toHaveText('The Sandbox Blocked the Web. DNS Had Other Ideas.');
  await expect(page.locator('.report-metrics')).toContainText('4/17');
  await expect(page.locator('.version-list > details')).toHaveCount(2);
  await page.locator('.alternate-editorial > summary').click();
  await expect(page.locator('.alternate-editorial h3')).toHaveText('The Model Found the DNS Side Door');
  await page.goto('/#/incidents/2026-09-24-openai-medicare-agent');
  await expect(page.locator('.report-metrics')).toContainText('9/17');
  await expect(page.locator('.version-list > details')).toHaveCount(3);
  await expect(page.locator('.variant-note')).toContainText('count the event once');
  await page.locator('.alternate-editorial > summary').click();
  await expect(page.locator('.alternate-editorial h3')).toHaveCount(2);
  await expect(page.locator('.alternate-editorial')).toContainText('The Research Agent Found the Staff-Only Door');
  await page.goto('/#/incidents/2026-09-12-amodei-slowdown-warning');
  await expect(page.getByRole('heading', { name: 'The recorded development.' })).toBeVisible();
  await expect(page.locator('.editorial-pending')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Why it matters.' })).toHaveCount(0);
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
  expect(overflow).toBe(false);
  expect(errors).toEqual([]);
});

test('methodology calculator, worked examples, downloads, and responsive layout', async ({ page }) => {
  await page.goto('/#/methodology');
  await expect(page.locator('h1')).toBeVisible();
  await expect(page.locator('.method-projected-time')).toHaveText('0%');
  await expect(page.locator('.method-calculator-output')).toContainText('27:25');
  const trifecta = page.locator('.method-toggle input');
  await expect(trifecta).toHaveCount(3);
  const expectedShares = ['0.69%', '2.06%', '4.74%'];
  const labels = await page.locator('.method-toggle').all();
  for (let index = 0; index < labels.length; index++) {
    await labels[index].click();
    await expect(page.locator('.method-projected-time')).toHaveText(expectedShares[index]);
  }
  for (const input of await trifecta.all()) await expect(input).toBeChecked();
  await expect(page.locator('.method-output-alert')).toBeVisible();
  await expect(page.locator('.method-projected-time')).toHaveText('4.74%');
  await expect(page.locator('.method-calculator-severity dd')).toHaveText('CRITICAL');
  await expect(page.locator('.method-calculator-output')).toContainText('7 / 17');
  const autonomy = page.locator('.method-stepper').nth(1);
  await autonomy.locator('label').nth(1).click();
  await expect(page.locator('.method-projected-time')).toHaveText('5.39%');
  await expect(page.locator('.method-calculator-output')).toContainText('8 / 17');
  await autonomy.locator('label').nth(2).click();
  await expect(page.locator('.method-projected-time')).toHaveText('6.05%');
  await expect(page.locator('.method-calculator-output')).toContainText('9 / 17');
  for (const stepper of await page.locator('.method-stepper').all()) await stepper.locator('label').nth(2).click();
  await expect(page.locator('.method-projected-time')).toHaveText('11.12%');
  await expect(page.locator('.method-calculator-output')).toContainText('17 / 17');
  await expect(page.locator('.method-calculator-severity dd')).toHaveText('EXISTENTIAL');
  await page.locator('.method-toggle').last().click();
  await expect(page.locator('.method-calculator-output')).toContainText('13 / 17');
  await expect(page.locator('.method-calculator-severity dd')).toHaveText('EXISTENTIAL');
  await page.getByRole('button', { name: /Reset/i }).click();
  await expect(page.locator('.method-projected-time')).toHaveText('0%');
  await page.locator('.method-stepper').first().locator('label').nth(2).click();
  await expect(page.locator('.method-projected-time')).toHaveText('1.38%');
  await page.getByRole('button', { name: /Reset/i }).click();
  await page.getByRole('button', { name: 'Example 02' }).click();
  await expect(page.locator('.method-trifecta-note')).toBeVisible();
  await expect(page.locator('.method-example-report')).toContainText('10/17');
  await expect(page.locator('.method-example-impact')).toContainText('6.70%');
  const downloads = page.locator('.method-downloads a[download]');
  await expect(downloads).toHaveCount(2);
  for (const link of await downloads.all()) {
    const href = await link.getAttribute('href');
    const response = await page.request.get(href!);
    expect(response.ok()).toBe(true);
    const csv = await response.text();
    expect(csv).toContain('cve_id');
    expect(csv).toContain((await link.textContent())?.includes('Assessment') ? 'Sanders and Casar' : 'The Model Found the DNS Side Door');
  }
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
  expect(overflow).toBe(false);
});

test('main pages render with local assets and unknown links recover', async ({ page }, testInfo) => {
  const failed: string[] = [];
  page.on('response', (response) => { if (response.status() >= 400 && response.url().includes('127.0.0.1')) failed.push(response.url()); });
  await page.goto('/');
  await page.evaluate(() => document.fonts.ready);
  expect(await page.evaluate(() => document.fonts.check('600 24px "Barlow Condensed"'))).toBe(true);
  await expect(page.locator('body')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('home.png'), fullPage: true });
  await page.goto('/#/incidents');
  await page.screenshot({ path: testInfo.outputPath('archive.png'), fullPage: true });
  await page.goto('/#/methodology');
  await expect(page.locator('body')).not.toContainText(/METHOD 02|Version 2\.0|LEGACY WORKFLOW|EXCLUDED FROM V2|methodology v2/i);
  await page.screenshot({ path: testInfo.outputPath('methodology.png'), fullPage: true });
  await page.goto('/#/incidents/not-a-real-record');
  await expect(page.getByRole('heading', { name: 'This report isn’t on the record.' })).toBeVisible();
  await page.getByRole('link', { name: 'Return to the archive' }).click();
  await expect(page.locator('.archive-row')).toHaveCount(40);
  expect(failed).toEqual([]);
});
