import type { Incident as IncidentRecord } from '../lib/types';
import { CRITERIA, formatTime } from '../lib/index';
import { Arrow, dateLabel, movementLabel, SeverityBadge, TextParagraphs } from '../components/Shared';

export default function Incident({ incident }: { incident: IncidentRecord }) {
  const assessment = incident.assessment;
  return <article className="container report-page"><a href="#/incidents" className="text-link report-back">← Back to the archive</a>
    <header className="report-header"><div className="report-metadata"><SeverityBadge severity={assessment.severity} score={assessment.score} /><span>{assessment.cveId} · {dateLabel(assessment.date, true)}</span></div><h1>{incident.headline}</h1>{incident.editorial?.metadata && <p>{incident.editorial.metadata}</p>}<a className="source-link" href={assessment.sourceUrl} target="_blank" rel="noopener noreferrer">Read the original source · {new URL(assessment.sourceUrl).hostname.replace('www.', '')} <Arrow diagonal /></a></header>
    <div className="report-metrics"><div><span className="mono-label">INCIDENT SCORE</span><strong>{assessment.score}<small>/13</small></strong></div><div><span className="mono-label">EVIDENCE POINTS</span><strong>{incident.effectivePoints}<small>{assessment.fullTrifecta ? 'TRIFECTA FLOOR' : 'ADDED TO INDEX'}</small></strong></div><div><span className="mono-label">COMPUTED MOVEMENT</span><strong>{movementLabel(incident.movementSeconds)}</strong></div><div><span className="mono-label">POSITION AFTER EVENT</span><strong>{formatTime(incident.remainingSeconds)}<small>SYMBOLIC MINUTES</small></strong></div></div>
    {incident.editorial && !incident.editorialMatchesAssessment && <aside className="editorial-version-note"><strong>Original editorial · earlier assessment</strong><p>The report below was written for the {incident.editorialAssessmentScore ?? 'previous'}-point assessment. The displayed {assessment.score}-point version is the assessment used by the current clock. Both versions are preserved below.</p></aside>}
    <div className="report-body"><div className="report-prose"><section><div className="eyebrow">01 / THE STORY</div><h2>{incident.editorial ? 'What happened.' : 'The recorded development.'}</h2><TextParagraphs text={incident.editorial?.story ?? assessment.title} />{!incident.editorial && <p className="editorial-pending">This event has a scored assessment. A full editorial report has not yet been published.</p>}</section>{incident.editorial && <section className="our-take"><div className="eyebrow">02 / OUR TAKE</div><h2>Why it matters.</h2><TextParagraphs text={incident.editorial.take} /></section>}{assessment.leadingIndicator && <aside className="leading-note"><span>↗</span><div><h3>A leading indicator.</h3><p>{assessment.leadingNote || 'This development may be significant beyond the direct capability changes reflected in its score.'}</p></div></aside>}<section className="scoring-notes"><div className="eyebrow">SCORING NOTES / ROOM FOR DISAGREEMENT</div><TextParagraphs text={assessment.notes} /></section></div>
      <aside className="assessment-panel"><div className="eyebrow">THE ASSESSMENT</div><h2>Show your working.</h2><p>Every point needs a reason.</p>{(['trifecta', 'amplifier'] as const).map((tier) => <div className="criterion-group" key={tier}><h3>{tier === 'trifecta' ? '01 / THE LETHAL TRIFECTA' : '02 / THE AMPLIFIERS'}</h3>{CRITERIA.filter((criterion) => criterion.tier === tier).map((criterion) => <details key={criterion.key} className="criterion-detail"><summary><span>{criterion.shortLabel}</span><span className="criterion-value">{Array.from({ length: criterion.max }, (_, index) => <i key={index} className={assessment.scores[criterion.key] > index ? 'active' : ''} />)}<b>{assessment.scores[criterion.key]}/{criterion.max}</b><span className="detail-plus">+</span></span></summary><p>{assessment.rationales[criterion.key]}</p></details>)}</div>)}{assessment.fullTrifecta && <div className="trifecta-alert">ALL THREE CONDITIONS PRESENT<br /><span>Severity is floored at CRITICAL. Evidence points are floored at 7.</span></div>}<a className="text-link" href="#/methodology">Read the full methodology <Arrow diagonal /></a></aside>
    </div>
    <section className="record-provenance"><div className="section-heading"><div><div className="eyebrow">THE RECORD / METHOD 02</div><h2>Nothing behind the curtain.</h2></div></div><p>Movements are recomputed from the current dataset in event-date order. They are not the clock positions originally published by the workflow. The source data and original assessment versions remain available.</p>{incident.assessments.length > 1 && <p className="variant-note">This development was assessed {incident.assessments.length} times. An explicit import review selected the displayed assessment; the event contributes once. Editorial wording may reflect a different original score.</p>}<p>{incident.selectionRationale}</p><div className="version-list">{incident.assessments.map((version, index) => <details key={`${version.cveId}-${index}`}><summary><span>{version.cveId} · {version.score}/13 · {version.severity}</span><span>{version === assessment ? 'DISPLAYED VERSION' : 'ORIGINAL VARIANT'} +</span></summary><p>{version.title}</p><p>{version.notes}</p><p className="mono-label">LEGACY WORKFLOW MOVEMENT: +{version.legacyMinutes} MINUTES · EXCLUDED FROM V2 CALCULATION</p><div className="version-rationales">{CRITERIA.map((criterion) => <p key={criterion.key}><strong>{criterion.label} · {version.scores[criterion.key]}/{criterion.max}</strong><br />{version.rationales[criterion.key]}</p>)}</div></details>)}</div>{incident.editorials.length > 1 && <details className="alternate-editorial"><summary>Read the other original editorial report ({incident.editorials.length - 1})</summary>{incident.editorials.filter((editorial) => editorial !== incident.editorial).map((editorial, index) => <div key={index}><h3>{editorial.headline}</h3><h4>The story</h4><TextParagraphs text={editorial.story} /><h4>Our take</h4><TextParagraphs text={editorial.take} /></div>)}</details>}<a href="#/methodology" className="text-link">Download the source data <Arrow diagonal /></a></section>
  </article>;
}
