import type { Incident as IncidentRecord } from '../lib/types';
import { formatTime, formatGapClosedPercent } from '../lib/calibration';
import { CRITERIA } from '../lib/criteria';
import { MAX_SCORE, calculateRiskScore } from '../lib/scoring';
import { Arrow, dateLabel, movementLabel, SeverityBadge, TextParagraphs } from '../components/Shared';

export default function Incident({ incident }: { incident: IncidentRecord }) {
  const assessment = incident.assessment;
  const scoring = incident.scoring;
  const isSelectedAssessment = (version: typeof assessment) => version.versionId && assessment.versionId
    ? version.versionId === assessment.versionId
    : version === assessment;
  const isSelectedEditorial = (version: NonNullable<typeof incident.editorial>) => version.versionId && incident.editorial?.versionId
    ? version.versionId === incident.editorial.versionId
    : version === incident.editorial;
  return <article className="container report-page"><a href="#/incidents" className="text-link report-back">← Back to the archive</a>
    <header className="report-header"><div className="report-metadata"><SeverityBadge severity={scoring.severity} score={scoring.totalPoints} /><span>{incident.publicId ?? assessment.cveId} · {dateLabel(assessment.date, true)}</span></div><h1>{incident.headline}</h1>{incident.editorial?.metadata && <p>{incident.editorial.metadata}</p>}<a className="source-link" href={assessment.sourceUrl} target="_blank" rel="noopener noreferrer">Read the original source · {new URL(assessment.sourceUrl).hostname.replace('www.', '')} <Arrow diagonal /></a></header>
    <div className="report-metrics"><div><span className="mono-label">INCIDENT SCORE</span><strong>{scoring.totalPoints}<small>/{MAX_SCORE}</small></strong></div><div><span className="mono-label">POINT BREAKDOWN</span><strong>{scoring.trifectaPoints} + {scoring.amplifierPoints}<small className="movement-context">TRIFECTA + AMPLIFIERS</small></strong></div><div><span className="mono-label">REMAINING GAP CLOSED</span><strong>{formatGapClosedPercent(incident.gapClosedPercent)}<small className="movement-context">{movementLabel(incident.movementSeconds)} AT THIS POINT</small></strong></div><div><span className="mono-label">POSITION AFTER EVENT</span><strong>{formatTime(incident.remainingSeconds)}<small>SYMBOLIC MINUTES</small></strong></div></div>
    <p className="impact-explainer">The same effective score closes the same share of the remaining symbolic gap. The seconds moved depend on the clock’s position.</p>
    {incident.editorial && !incident.editorialMatchesAssessment && <aside className="editorial-version-note"><strong>Assessment note</strong><p>The report below accompanies a {incident.editorialAssessmentScore ?? 'separate'}-point assessment. The clock uses the selected {scoring.totalPoints}-point assessment. Both assessments and their rationales are available below.</p></aside>}
    <div className="report-body"><div className="report-prose"><section><div className="eyebrow">01 / THE STORY</div><h2>{incident.editorial ? 'What happened.' : 'The recorded development.'}</h2><TextParagraphs text={incident.editorial?.story ?? assessment.title} />{!incident.editorial && <p className="editorial-pending">This event has a scored assessment. A full editorial report has not yet been published.</p>}</section>{incident.editorial && <section className="our-take"><div className="eyebrow">02 / OUR TAKE</div><h2>Why it matters.</h2><TextParagraphs text={incident.editorial.take} /></section>}{assessment.leadingIndicator && <aside className="leading-note"><span>↗</span><div><h3>A leading indicator.</h3><p>{assessment.leadingNote || 'This development may be significant beyond the direct capability changes reflected in its score.'}</p></div></aside>}<section className="scoring-notes"><div className="eyebrow">SCORING NOTES / ROOM FOR DISAGREEMENT</div><TextParagraphs text={assessment.notes} /></section></div>
      <aside className="assessment-panel"><div className="eyebrow">THE ASSESSMENT</div><h2>Show your working.</h2><p>Every point needs a reason.</p>{(['trifecta', 'amplifier'] as const).map((tier) => <div className="criterion-group" key={tier}><h3>{tier === 'trifecta' ? '01 / THE LETHAL TRIFECTA' : '02 / THE AMPLIFIERS'}<span>{tier === 'trifecta' ? `${scoring.trifectaCount}/3 ACTIVE · ${scoring.trifectaPoints}/7 POINTS` : `${scoring.amplifierPoints}/10 POINTS`}</span></h3>{CRITERIA.filter((criterion) => criterion.tier === tier).map((criterion) => <details key={criterion.key} className="criterion-detail"><summary><span>{criterion.shortLabel}</span><span className="criterion-value">{Array.from({ length: criterion.max }, (_, index) => <i key={index} className={assessment.scores[criterion.key] > index ? 'active' : ''} />)}<b>{criterion.tier === 'trifecta' ? (assessment.scores[criterion.key] ? 'ON' : 'OFF') : `${assessment.scores[criterion.key]}/${criterion.max}`}</b><span className="detail-plus">+</span></span></summary><p className="criterion-definition">{criterion.description}</p>{criterion.scoreDescriptions && <ol className="criterion-rubric" start={0}>{criterion.scoreDescriptions.map((description, value) => <li key={value}>{description}</li>)}</ol>}<p>{assessment.rationales[criterion.key]}</p></details>)}</div>)}{assessment.fullTrifecta && <div className="trifecta-alert">ALL THREE CONDITIONS PRESENT<br /><span>The Trifecta contributes 7 points, guaranteeing at least CRITICAL. Every amplifier point is added on top.</span></div>}<a className="text-link" href="#/methodology">Read the full methodology <Arrow diagonal /></a></aside>
    </div>
    <section className="record-provenance"><div className="section-heading"><div><div className="eyebrow">THE RECORD / METHODOLOGY</div><h2>Nothing behind the curtain.</h2></div></div><p>The clock is calculated from each weighted score in assessment-date order. The percentage of the gap closed depends on this incident’s score; its movement in seconds also depends on where it falls in the sequence.</p>{incident.assessments.length > 1 && <p className="variant-note">This development has {incident.assessments.length} assessments. We use one selected assessment and count the event once.</p>}<p>{incident.selectionRationale}</p><div className="version-list">{incident.assessments.map((version, index) => {
      const result = calculateRiskScore(version.scores);
      return <details key={version.versionId ?? `${version.cveId}-${index}`}><summary><span>{version.cveId} · {result.totalPoints}/{MAX_SCORE} · {result.severity === 'NO_MOVEMENT' ? 'NO MOVEMENT' : result.severity}</span><span>{isSelectedAssessment(version) ? 'SELECTED ASSESSMENT' : 'OTHER ASSESSMENT'} +</span></summary><p>{version.title}</p><p>{version.notes}</p><div className="version-rationales">{CRITERIA.map((criterion) => <p key={criterion.key}><strong>{criterion.label} · {criterion.tier === 'trifecta' ? (version.scores[criterion.key] ? 'active' : 'inactive') : `${version.scores[criterion.key]}/${criterion.max}`}</strong><br />{version.rationales[criterion.key]}</p>)}</div></details>;
    })}</div>{incident.editorials.length > 1 && <details className="alternate-editorial"><summary>Additional editorial reports ({incident.editorials.length - 1})</summary>{incident.editorials.filter((editorial) => !isSelectedEditorial(editorial)).map((editorial, index) => <div key={editorial.versionId ?? index}><h3>{editorial.headline}</h3><h4>The story</h4><TextParagraphs text={editorial.story} /><h4>Our take</h4><TextParagraphs text={editorial.take} /></div>)}</details>}<a href="#/methodology" className="text-link">Download the source data <Arrow diagonal /></a></section>
  </article>;
}
